@rootURL = http://localhost:5218

GET {{rootURL}}/api/Vegetable
Accept: application/json

###
GET {{rootURL}}/api/Vegetable/4

###
POST {{rootURL}}/api/Vegetable
content-type: application/json
{
  "name": "Garlic",
  "origin": "Local farm: Sokoto, Nigeria",
  "price": 78.99,
  "ripeOrNot": true,
  "dateAvailable": "2024-06-01"
}

###
PUT {{rootURL}}/api/Vegetable/11
Content-Type: application/json
{
  "name": "Garden egg",
  "origin": "Local farm: Nkawkaw",
  "price": 50.00,
  "ripeOrNot": false,
  "dateAvailable": "2026-10-04"
}

###
DELETE {{rootURL}}/api/Vegetable/11